import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Middleware Context Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Middleware Context Demo</h1>

        <p className={styles.description}>
          Check <code className={styles.code}>middleware.js</code> to see how
          context <code className={styles.code}>foo</code> is set to{" "}
          <code className={styles.code}>bar</code>.
        </p>

        <div className={styles.grid}>
          <Link href="/api/node">
            <a className={styles.card}>
              <h2>API on Node &rarr;</h2>
              <p>
                Test <code className={styles.code}>getContext</code> in a API
                route on the node runtime.
              </p>
            </a>
          </Link>

          <Link href="/api/edge">
            <a className={styles.card}>
              <h2>API on Edge &rarr;</h2>
              <p>
                Test <code className={styles.code}>getContext</code> in a API
                route on the edge runtime.
              </p>
            </a>
          </Link>

          <Link href="/node">
            <a className={styles.card}>
              <h2>Page on Node &rarr;</h2>
              <p>
                Test <code className={styles.code}>getContext</code> in a page
                on the Node runtime.
              </p>
            </a>
          </Link>

          <Link href="/edge">
            <a className={styles.card}>
              <h2>Page on Edge &rarr;</h2>
              <p>
                Test <code className={styles.code}>getContext</code> in a page
                on the edge runtime.
              </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/clerkinc/nextjs-context-example"
          target="_blank"
          rel="noopener noreferrer"
        >
          See the code on Github
        </a>
      </footer>
    </div>
  );
}
